# Generated by Django 4.2.6 on 2023-11-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentik.stock'),
        ),
    ]
