# Generated by Django 4.2.6 on 2023-11-07 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentik', '0004_historicalstockprices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalStockPrices',
            new_name='HistoricalStockPrice',
        ),
    ]
