# Generated by Django 4.2.6 on 2023-11-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik', '0005_rename_historicalstockprices_historicalstockprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='pnl',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
