# Generated by Django 4.2.6 on 2023-11-08 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentik', '0006_portfolio_pnl_alter_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 8, 11, 38, 56, 633037)),
            preserve_default=False,
        ),
    ]
